HealthPal/Controllers/AdminSpecialistController.cs
using HealthPal.Models;
using HealthPal.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace HealthPal.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AdminSpecialistController : Controller
    {
        private readonly IAdminSpecialistRepo AdminSpecialistRepository;
        public AdminSpecialistController(IAdminSpecialistRepo adminSpecialistRepo)
        {
            AdminSpecialistRepository = adminSpecialistRepo;
        }
        [Route("GetAllSpecialists")]
        public ActionResult GetAllSpecialists()
        {
            return View(AdminSpecialistRepository.GetAllSpecialists());
        }
       
        [Route("Details/{id:min(1)}")]
        public ActionResult Details(int id)
        {
            return View(AdminSpecialistRepository.GetSpecialistById(id));
        }

        public IActionResult CreateSpecialist()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateSpecialist(Specialist specialist)
        {
            if (ModelState.IsValid)
            {
                await AdminSpecialistRepository.AddSpecialistAsync(specialist);
                return RedirectToAction("GetAllSpecialists");
            }
            return View(specialist);
        }

        [Route("Edit/{id:min(1)}")]
        public ActionResult Edit(int id)
        {
            return View(AdminSpecialistRepository.GetSpecialistById(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("Edit/{id:min(1)}")]
        public async Task<IActionResult> Edit(int id, Specialist specialist)
        {
            if (ModelState.IsValid)
            {
                await AdminSpecialistRepository.EditSpecialistAsync(id, specialist);
                return RedirectToAction("GetAllSpecialists");
            }
            return View(specialist);
        }

        [Route("Delete/{id:min(1)}")]
        public ActionResult Delete(int id)
        {
            return View(AdminSpecialistRepository.GetSpecialistById(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("Delete/{id:min(1)}")]
        public ActionResult Delete(int id, Specialist specialist)
        {
            AdminSpecialistRepository.DeleteSpecialist(id);
            return RedirectToAction("GetAllSpecialists");
        }
    }
}

HealthPal/Controllers/DoctorController.cs
using HealthPal.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace HealthPal.Controllers
{
    [AllowAnonymous]
    public class DoctorController : Controller
    {
        public IDoctorRepo DoctorContext { get; set; }
        public IRatingRepo RatingContext { get; set; }
        public DoctorController(IDoctorRepo doctorContext,IRatingRepo rating)
        {
            DoctorContext = doctorContext;
            RatingContext = rating;
        }
        public IActionResult GetDoctorsInSpecialist(int id)
        {
            return View(DoctorContext.GetDoctorsAccordingSpecialist(id));
        }

        public IActionResult GetDoctorById(int id)
        {
            ViewBag.Reviews = RatingContext.GetAllRatingsForDoc(id).ToList();
            return View(DoctorContext.GetDoctortData(id));
        }
    }
}

HealthPal/Views/AdminSpecialist/CreateSpecialist.cshtml
@model HealthPal.Models.Specialist

@{
    ViewData["Title"] = "CreateSpecialist";
}

<h1>CreateSpecialist</h1>

<h4>Specialist</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateSpecialist" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageFile"></label>
                <input asp-for="ImageFile" type="file" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="GetAllSpecialists">Back to List</a>
</div>

HealthPal/Views/AdminSpecialist/Delete.cshtml
@model HealthPal.Models.Specialist

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Specialist</h4>
    <hr />
    <div class="card" style="width: 18rem;">
        <img src="data:image/png;base64,@Convert.ToBase64String(Model.Image)" alt="Specialist Image" class="card-img-top" />
        <div class="card-body">
            <h5 class="card-title">@Model.Name</h5>
            <a asp-controller="Doctor" asp-action="GetDoctorsInSpecialist" asp-route-id="@Model.ID" class="btn btn-primary">Go Doctors</a>
        </div>
    </div>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="GetAllSpecialists">Back to List</a>
    </form>
</div>

HealthPal/Views/AdminSpecialist/Details.cshtml
@model HealthPal.Models.Specialist

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Specialist</h4>
    <hr />
    <div class="card" style="width: 18rem;">
        <img src="data:image/png;base64,@Convert.ToBase64String(Model.Image)" alt="Specialist Image" class="card-img-top" />
        <div class="card-body">
            <h5 class="card-title">@Model.Name</h5>
            <a asp-controller="Doctor" asp-action="GetDoctorsInSpecialist" asp-route-id="@Model.ID" class="btn btn-primary">Go Doctors</a>
        </div>
    </div>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.ID">Edit</a> |
    <a asp-action="GetAllSpecialists">Back to List</a>
</div>

HealthPal/Views/AdminSpecialist/Edit.cshtml
@model HealthPal.Models.Specialist

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Specialist</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateSpecialist" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageFile"></label>
                <input asp-for="ImageFile" type="file" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="GetAllSpecialists">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

HealthPal/Views/AdminSpecialist/GetAllSpecialists.cshtml
@model IEnumerable<HealthPal.Models.Specialist>

@{
    ViewData["Title"] = "GetAllSpecialists";
}

<h1>GetAllSpecialists</h1>

<p>
    <a asp-action="CreateSpecialist">Create New</a>
</p>
<h1 class="text-center fw-bold text-primary">Specialties</h1>

<div class="d-flex flex-wrap gap-3 justify-content-center">
    @foreach (var item in Model)
    {
        <div class="card" style="width: 18rem;">
            <img src="data:image/png;base64,@Convert.ToBase64String(item.Image)" alt="Specialist Image" class="card-img-top" />
            <div class="card-body">
                <h5 class="card-title">@item.Name</h5>
                <a asp-controller="Doctor" asp-action="GetDoctorsInSpecialist" asp-route-id="@item.ID" class="btn btn-primary">Go Doctors</a>
            </div>
        </div>
    }
</div>