HealthPal/Models/Doctor.cs
using Microsoft.AspNetCore.Identity;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Diagnostics.CodeAnalysis;
using System.Xml;

namespace HealthPal.Models
{
    [Table("Doctor")]
    public class Doctor
    {

        [Key]
        public int ID { get; set; }
        [Required(ErrorMessage = "Enter Your First Name")]
        [Display(Name = "First Name")]
        [MinLength(3, ErrorMessage = "First Name Must be At Least 3 Characters")]
        [MaxLength(10, ErrorMessage = "First Name Must`t be Exceed 10 Characters")]
        public string FName { get; set; }
        [Required(ErrorMessage = "Enter Your Last Name")]
        [Display(Name = "Last Name")]
        [MinLength(3, ErrorMessage = "Last Name Must be At Least 3 Characters")]
        [MaxLength(10, ErrorMessage = "Last Name Must`t be Exceed 10 Characters")]
        public string LName { get; set; }
      
        public DateTime BDate { get; set; }
        public string? Phone { get; set; }
        public string? Image { get; set; }
        [NotMapped]
        public IFormFile? ImageFile { get; set; } 
        [AllowNull]
        public byte[]? ImageData { get; set; }
        
        [DataType(DataType.MultilineText)]
        public string? Description { get; set; }
        
        [ForeignKey("Specialist")]
        public int? SpecialistID { get; set; }
        public virtual Specialist? Specialist { get; set; }
        public virtual List<Time>? DoctorAppointments { get; set; }
        public virtual List<Appointment>? ReservedAppointments { get; set; }
        [ForeignKey("User")]
        public string User_Id { get; set; }
        public ApplicationUser? User { get; set; }

   

    }
}

HealthPal/Controllers/DoctorController.cs
using HealthPal.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace HealthPal.Controllers
{
    [AllowAnonymous]
    public class DoctorController : Controller
    {
        public IDoctorRepo DoctorContext { get; set; }
        public IRatingRepo RatingContext { get; set; }
        public DoctorController(IDoctorRepo doctorContext,IRatingRepo rating)
        {
            DoctorContext = doctorContext;
            RatingContext = rating;
        }
        public IActionResult GetDoctorsInSpecialist(int id)
        {
            return View(DoctorContext.GetDoctorsAccordingSpecialist(id));
        }

        public IActionResult GetDoctorById(int id)
        {
            ViewBag.Reviews = RatingContext.GetAllRatingsForDoc(id).ToList();
            return View(DoctorContext.GetDoctortData(id));
        }
    }
}

HealthPal/Controllers/ReviwController.cs
using HealthPal.Models;
using HealthPal.Repositories;
using HealthPal.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using System.Security.Cryptography;

namespace HealthPal.Controllers
{
    [Authorize(Roles = "Admin,Patient")]
    public class ReviwController : Controller
    {
        private IRatingRepo _RatingRepo { get; }
        private IPatientRepo _patientRepo { get; }
        public ReviwController(IRatingRepo ratingrepo, IPatientRepo patientRepo)
        {
            _RatingRepo = ratingrepo;
            _patientRepo = patientRepo;
        }

        public IActionResult GetAllDocReviews(int DId)
        {
            return View(_RatingRepo.GetAllRatingsForDoc(DId));
        }

        private int getpatientid()
        {
            string UId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            return _patientRepo.GetPatientIdUsingUserID(UId);
        }

        [HttpGet]
        public IActionResult PatientWriteReview(int id)
        {
            ViewBag.P_Id = getpatientid();
            ViewBag.D_Id = id;
            return View(new ReviewViewModel());
        }
        [HttpPost]
        public IActionResult PatientWriteReview(ReviewViewModel PRating)
        {
            Rating rating = new Rating();
            rating.DID = int.Parse(PRating.DID);
            rating.PID = int.Parse(PRating.PID);
            rating.Rate = PRating.Rate;
            rating.Review = PRating.Review;
            if (ModelState.IsValid)
            {
                _RatingRepo.CreateRating(rating);
                return View(new ReviewViewModel()); 
            }

            return View();
        }

        [HttpGet]
        public IActionResult PatientEditReview(int PId,int DId)
        {
            return View(_RatingRepo.GetPatientRatingForDoc(PId, DId));
        }
        [HttpPost]
        public IActionResult PatientEditReview(int PId,Rating PRating)
        {

            if (ModelState.IsValid)
            {
                _RatingRepo.EditRating(PId, PRating);
                return RedirectToAction("GetAllDocReviews");
            }
            return View(_RatingRepo.GetPatientRatingForDoc(PId, PRating.DID));
        }
        public IActionResult PatientDeleteReview(int PId, Rating PRating)
        {
            if (ModelState.IsValid)
            {
                _RatingRepo.DeleteRating(PId, PRating);
                return RedirectToAction("GetAllDocReviews");
            }
            return View();
        }
       

    }
}

HealthPal/Views/Doctor/GetDoctorById.cshtml
@model HealthPal.Models.Doctor


@{
    ViewData["Title"] = "GetDoctorById";
   
}

<h1 class="text-center fw-bold text-primary">Dr.@Model.FName  @Model.LName</h1>
<div class="card m-auto" style="width: 70%;">
    <img src="/img/@Model.Image" class="card-img-top" alt="...">
    <div class="card-body">
        <h5 class="card-title">Dr.@Model.FName @Model.LName</h5>
        <p class="card-text">@Model.Description</p>
    </div>
    <ul class="list-group list-group-flush">
        <li class="list-group-item">@Model.Specialist.Name</li>
    </ul>
    <div class="card-body">
        <a asp-controller="Appointment" asp-action="CreateAppointment" asp-route-id="@Model.ID" class="btn btn-primary">Appointment</a>
        <a asp-action="PatientWriteReview" asp-controller="Reviw" asp-route-id="@Model.ID" class="btn btn-primary">Add Review</a>
    </div>
</div>
<br />
<h2 class="text-center fw-bold text-primary">Reviews</h2>
@foreach (var item in (List<Rating>)ViewBag.Reviews)
{
    <div class="card m-auto" style="width:60%">
        <div class="card-header">
            @item.Patient.FName @item.Patient.LName
        </div>
        <div class="card-body">
            <blockquote class="blockquote mb-0">
                <p>@item.Review</p>
                <footer class="blockquote-footer"><i class="fas fa-star"></i> <cite title="Source Title">@item.Rate</cite></footer>
            </blockquote>
        </div>
    </div>
    <br />
}

HealthPal/Views/Doctor/GetDoctorsInSpecialist.cshtml
@model IEnumerable<HealthPal.Models.Doctor>

@{
    ViewData["Title"] = "GetDoctorsInSpecialist";
}

<h1 class="text-center fw-bold text-primary">@Model.FirstOrDefault().Specialist.Name</h1>
<div class="d-flex justify-content-center">
<div class="d-flex flex-column">
@foreach(var item in Model)
{
    <div class="card mb-3" style="max-width: 940px;">
        <div class="row g-0">
            <div class="col-md-4">
                <img src="/img/@item.Image" width="300px" height="270px" class="rounded-start" alt="...">
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <h5 class="card-title">Dr.@item.FName @item.LName</h5>
                            @* <div class="d-flex align-items-center mb-2">
                                <span class="star-rating">
                                    <i class="fas fa-star"></i>
                                    <i class="fas fa-star"></i>
                                    <i class="fas fa-star"></i>
                                    <i class="fas fa-star-half-alt"></i>
                                    <i class="far fa-star"></i>
                                </span>
                            </div> *@
                    <p class="card-text text-secondary">@item.Description</p>
                    @* <p class="card-text"><small class="text-body-secondary"></small></p> *@<br />
                            <a asp-action="GetDoctorById" asp-route-id="@item.ID" class="btn btn-primary">Details</a>
                </div>
            </div>
        </div>
    </div>
}
</div>
</div>

HealthPal/Views/Doctor/TopRatedDoctors.cshtml
@model Dictionary<HealthPal.Models.Specialist, List<HealthPal.Models.Rating>>

<h2>Top Rated Doctors in Each Specialist</h2>

@foreach (var pair in Model)
{
    <h3>@pair.Key.Name</h3>
    <table class="table">
        <thead>
            <tr>
                <th>Doctor Name</th>
                <th>Average Rating</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var rating in pair.Value)
            {
                <tr>
                    <td>@rating.Doctor.FName @rating.Doctor.LName</td>
                    <td>@rating.Rate</td>
                </tr>
            }
        </tbody>
    </table>
}